name: issue_open
on:
  issues:
    types: [opened]
env:
  variable: 'issue créée'
jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: push
        run: echo $variable