name: pushpull
on: [push]
env:
  variable: C'est un push!
on: [pull]
env:
  variable2: C'est une pull request!
jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: push
        run: echo $variable
  jobs2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull
        run: echo $variable2